services:
  agrix_backend:
    build:
        context: .
    ports:
      - 8080:8080
    depends_on:
        - agrix_mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://agrix_mysql:3306/alexandriadb?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.MySQLDialect
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"


  agrix_mysql:
    image: mysql:8.0.32
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: alexandriadb